{{- if .Values.onepassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "dayspassed-bot.onepasswordItemName" . }}
  labels:
    {{- include "dayspassed-bot.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.onepassword.itemPath | quote }}
{{- end }}