apiVersion: v2
name: daypassed-bot
description: A Helm chart for deploying the daypassed-bot as a Kubernetes CronJob.
type: application
sources:
  - https://github.com/Soli0222/daypassed-bot
version: 0.1.1
appVersion: "1.2.1"
